version: "3.8"
services:
  front-end:
    container_name: frontend-container
    build:
      context: ./client/client
      dockerfile: dockerfile
    #image: lamnguyen0206/frontend
    ports:
      - "3000:80"
    networks:
      - video-analysis
    depends_on:
      - back-end
  database:
    container_name: mongodb
    image: mongo
    ports:
      - 27018:27017
    command: mongod --bind_ip_all
    networks:
      - video-analysis
    volumes:
      - mongodb_data:/data/db

  back-end:
    container_name: backend-container
    # build:
    #   context: ./server/video-editing-api/video-editing-api
    #   dockerfile: Dockerfile
    image: lamnguyen0206/backend
    ports:
      - 5001:80  
    depends_on:
      - database
    networks:
      - video-analysis
  
networks:
  video-analysis:
    driver: bridge
    
volumes:
  mongodb_data:
  